### ISSUE TITLE
How to have Deck UI on other distro?

### ISSUE THREAD

**Issue by wmd0701** [ShadowBlip/HandyPT#13]
Hi there! Firstly, great thanks for your excellent work!

While in the readme file it is mentioned that HandyPT can be used with Deck UI on any distro which supports flatpak and gamescope, I have no idea how to have Deck UI run on other disto. There are some tutorials for Deck UI (like [this one](https://www.reddit.com/r/SteamDeck/comments/t57l4t/how_to_get_the_steam_deck_ui_on_windowsany_linux/)), but it seems that such Deck UI does not support extensions. So no way to open crankshaft. Any help here? Thx :)

**Comment by pastaq** [comment]
You will need gamescope with a custom gamescope session and the proper boot parameters. This isn't the best forum for a how to for this issue though. Try reaching out on reddit or Discord.
