### ISSUE TITLE
5825U not boosting GPU

### ISSUE THREAD

**Issue by pacoa-kdbg** [ShadowBlip/HandyPT#14]
https://youtu.be/KRZR3Vy2IRw

Using latest version of all as today

**Comment by pastaq** [comment]
I'm not sure what I am supposed to be looking for here. With the device plugged in I can't see if the system battery draw is affected or not. That is the only way to really see if there is an effect. While your framerate doesn't change, it could be the game isn't very demanding and doesn't need full power. With the CPU Boost and SMT toggles working it would appear your configuration is correct.
