### ISSUE TITLE
need of help GPD winmax2 cannot be read correctly

### ISSUE THREAD

**Issue by danyi** [ShadowBlip/HandyPT#19]
![image](https://user-images.githubusercontent.com/1498746/201094089-5a99b026-22ca-4d73-b458-80a971f86ba7.png)

![image](https://user-images.githubusercontent.com/1498746/201093680-7ad1204e-5352-44ea-b8a2-9a4130e661b4.png)
 GPD winmax2 cannot be read correctly
I changed the parameters so he could recognize it
But it doesn't work

**Comment by pastaq** [comment]
Do you have a repo with the fork you're working on? I'll need to look at the code. It would also be better to open issues you are having with your fork within your forks repo and tag me in the discussion if you have questions. Issues here are supposed to be for branches of this repo. Please open an issue on your fork and tag me, I will be glad to assist.
