### ISSUE TITLE
HandyPT on Linux Steam app version : install successful but does not appear in UI

### ISSUE THREAD

**Issue by prog-amateur2** [ShadowBlip/HandyPT#22]
Hello I have tried to install HandyPT on a GPD Win 3 with Steam app in a Manjaro OS without success. 
Please find my installation process : 

1. Install Manjaro
2. Install Steam
3. Activate Beta channel (Settings > account > change > switch from normal to beta channel)
4. Activate BPM ("Big Picture Mode", to get the "Steam Deck" gamepad UI)
5. Install prerequisites (GLIBC, Crankshaft, wget)
7. This is where I have an issue : I can't find the Developer Mode in the gamepad UI so I can't get the Plugin section in the UI. 
-> So I install HandyPT version 0.3.0 (manual install) 
8. I switch to Desktop Mode and click on the Crankshaft logo, so I can and activate/reload HandyPT (**a notification says it is reloaded successfully**). 
![](https://crankshaft.space/docs/usage/quick-start/desktop-menu-button.png)

-> However HandyPT is not found on the gamepad UI's Quick settings > Crankshaft icon (I can only find audio/airplane mode settings, but no TDP settings) as in the below picture : 
![](https://steamuserimages-a.akamaihd.net/ugc/1809895086190884352/A5D79C610E167644240EF44D8E01FB377B7A7B2D/)

**Question :** 
Please do you know how to make HandyPT appear in the UI please, did I forgot something in the process or is it a bug ? 

Thank you very much for your kind help.

**Comment by pastaq** [comment]
Unfortunately Crankshaft is currently broken in gamepadui, so it's unable to inject the plugin into the QAM. We're waiting on an update for it but there's no ETA as the developer is having some personal issues. I'm exploring alternatives currently but it's a slow process.

**Comment by prog-amateur2** [comment]
Thanks a lot for your quick feedback. I hope he will solve his personal worries, it's more important than playing video games. 

Thank you also for looking for an alternative, it took me a while to understand that my problem was coming from a difference between gamepadui vs Steam Deck UI. 

Would you prefer that I close this issue or leave it open for tracking?

**Comment by pastaq** [comment]
I'll close it. I've added a note to the README for this issue.
