### ISSUE TITLE
Crankshaft does not appear

### ISSUE THREAD

**Issue by McWalters00** [ShadowBlip/HandyPT#23]
Crankshaft doesn’t work on the Steam deck ui it doesn’t appear so I can’t put the tdp limit

**Comment by pastaq** [comment]
Crankshaft is currently broken. Please read the note on the Readme.

**Comment by McWalters00** [comment]
> Crankshaft is currently broken. Please read the note on the Readme.
> 
> 

And do you have any idea of when it will work again like this month or in a longer time?

**Comment by pastaq** [comment]
No. All the information I have is on the README.
