### ISSUE TITLE
Intel Support

### ISSUE THREAD

**Issue by pastaq** [ShadowBlip/HandyPT#4]
Information is needed to write backend functionality for Intel handhelds. The following commands should provide the data to make backend calls for testing
`sudo dmesg | grep locked` if anything doesn't work may show if RAPL is locked by BIOS
`cat /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled` is RAPL config enabled?
`echo 1 | sudo tee /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled` can it be enabled?

Name/function of each constraint:
`cat /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_0_name`
`cat /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_1_name`
`cat /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_2_name`

Default values:
`cat /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw` 
`cat /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_power_limit_uw` 
`cat /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_2_power_limit_uw` 

Can we edit the contsraints?
`echo "8000000" | sudo tee /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw ` set to 8W

if there is anything in  `/sys/devices/virtual/powercap/intel-rapl` related to MMIO, newer chips use that and it might be a little different.
if it does it probably has both. its not well documented though so experimenting will be needed.

**Comment by ruineka** [comment]
![PXL_20220721_053553028~2.jpg](https://user-images.githubusercontent.com/16360335/180138301-4dc13cbf-34a4-4c23-aae0-00fe8cd5cb09.jpg)
