### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Koniasy** [ShadowBlip/HandyPT#5]
sudo sh
~/.var/app/space.crankshaft.Crankshaft/data/crankshaft/plugins/HandyPT/configure.sh

hello,my mechine is Onexplayer mini 5800u,i cannot continue when i do this step(after enter the code above),i dont know why.
help me,thank u very much!

**Comment by pastaq** [comment]
Did you do the manual install or through the crankshaft menu?

**Comment by pastaq** [comment]
Any update?
