### ISSUE TITLE
Cannot work properly at 6800U

### ISSUE THREAD

**Issue by danyi** [ShadowBlip/HandyPT#8]
I had the same problem with my GPD WINMAX2 6800U 
He can't work properly
I'm using steamos3.3

**Comment by pastaq** [comment]
6800U hasn't been added yet due to a lack of testers. Are you willing to test/validate safe limits on your device? I can add the basic values to the next release candidate for v0.2.0

**Comment by danyi** [comment]
No problem. I can do that.
