### ISSUE TITLE
68OOU does not work

### ISSUE THREAD

**Issue by danyi** [ShadowBlip/HandyPT#9]
![ZWR$YCZ8CZVF9~%F8G1G(FD](https://user-images.githubusercontent.com/1498746/184539622-ab45df72-7f74-451c-852b-ce5b3a7d5d93.png)
As you can see, it still doesn't work properly on my computer, which has a 6800U CPU

**Comment by danyi** [comment]
![~KS{A14}2ZH9G8$)K8ZT4D9](https://user-images.githubusercontent.com/1498746/184541425-ae4658fc-541d-4e9f-83b5-343cfd705481.png)
As indicated, I can adjust TPD manually to take effect

**Comment by pastaq** [comment]
Did you run the config script?

**Comment by danyi** [comment]
Yes, I did 
I did the following
cd ~/.var/app/space.crankshaft.Crankshaft/data/crankshaft/plugins/
wget https://github.com/ShadowBlip/HandyPT/files/9332441/handypt-v0.2.0.tar.gz
tar -xzf handypt-v0.2.0.tar.gz
sudo HandyPT/bin/configure.sh
Restart computer
In the DeckUI navigate to Plugins -> Manage Plugins -> Handheld Power Tools -> Load
Restart computer
it still doesn't work

but cpu bootsing and Similtanious Multthreading  it works

**Comment by pastaq** [comment]
Looks like RyzenAdj doesn't support the dump table function for 6800u from your picture above. Does -a set your STAPM?

**Comment by danyi** [comment]
Oh, yes

I use./ryzenadj --stapm-limit= 45,000 --fast-limit= 45,000 --slow-limit= 45,000 -- TCTL-temp =90

It works

**Comment by pastaq** [comment]
Okay, I think there may be a solution. There is a newer version of RyzenAdj that came out recently. We are on 0.10.0, 0.11.1 seems to have better support for Rembrandt. The -1 seems to indicate that the family is unknown in v0.10.0. How comfortable are you compiling from source to test on your device? If you can compile the latest release and validate the other commands we need I can do a hotfix to include v0.11.1.

https://github.com/FlyGoat/RyzenAdj

Without a major rewrite, and frankly bad practice of writing to the driver blind, it wont really work. I need to be able to see the --dump-table to verify the operation was successful and/or reflect when another program or feature changes the TDP.

**Comment by danyi** [comment]
I used the latest version, V0.11.1.
But it doesn't work

ryzenadj.exe -i
CPU Family: Rembrandt
SMU BIOS Interface Version: 18
Version: v0.11.1
request_table_ver_and_size is not supported on this family
Unable to init power metric table: -1, this does not affect adjustments because it is only needed for monitoring.

ryzenadj.exe --dump-table
request_table_ver_and_size is not supported on this family
Unable to init power metric table: -1, this does not affect adjustments because it is only needed for monitoring.

**Comment by pastaq** [comment]
Alright. We'll need to open a bug report on RyzenAdj.

**Comment by danyi** [comment]
https://github.com/FlyGoat/RyzenAdj/issues/210

**Comment by danyi** [comment]
Hi. I have an idea

Let him read the parameters in the configuration file

This allows you to set the TDP range manually

For example, I use software to set 6800U from 12W to 45W under WINDOWS

It will also be more versatile

This will not affect the automatic reading

The read values can also be saved to the configuration file

**Comment by pastaq** [comment]
I'll think about it, but I don't think that is the best approach. For one, I wouldn't be confident the settings actually took. Sometimes it doesn't actually work and the only way to tell is to parse the dump. Also, if something were to adjust the TDP behind the user it wouldn't be reflected. 

Another dev from ChimeraOS has the 6900HS. As soon as we get work fro FlyGoat what info he needs for the table we can get RyzenAdj fully supported. This will also benefit every other project using ryzenadj, which is quite a few actually.

**Comment by pastaq** [comment]
So based on the slow movement from the RyzenAdj team on providing the steps we need to reverse engineer that table, I've reworked my backend to save the last successful setting returned from RyzenAdj instead. This will need to be in the 0.3.0 release though as I've already started working on controller support and another rebase would cause some headaches. Should be released soon-ish, I'd guess a week, maybe two tops.

**Comment by danyi** [comment]
Thanks for your efforts

**Comment by pastaq** [comment]
I have released v0.3.0. This should work now for the 6600u, 6800u, and 6900hs. YOu can manually install or wait for the crankshaft update to be posted. When you have the opportunity to confirm operation please let me know if this works for you.

**Comment by danyi** [comment]
I have now updated V0.3.0. Now I can control TDP

But my current maximum is only 38W but my 6800U can reach 45W

How do I change it

**Comment by AaronBaird1** [comment]
@danyi I've noticed that I cant set more than 30w using ryzenadj on my 6800U (thinkbook 13s) based on battery drain since `ryzenadj -i` isnt working.  How are you measuring TDP btw?  the mangohud built into steamos?

**Comment by danyi** [comment]
I worked on my machine GPD WINMAX2 under Windows and it worked stably at 45W

So I'm sure I need 45W

**Comment by danyi** [comment]
The author did not return for a long time

I can't get in touch either

I modified the configuration file to get what I wanted

So I'm going to close this session

**Comment by pastaq** [comment]
Sorry, I've been at a training camp for work the last six weeks and haven't really had free time. I'll be back next week.

**Comment by danyi** [comment]
I'm glad to see you back

Your code has helped me a lot

How do I get in touch with you

**Comment by pastaq** [comment]
Here, or on the ChimeraOS discord.

**Comment by danyi** [comment]
It seemed time for me to try and learn about ChimeraOS
